site_name: Siddhi-Map-Text
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/extra.js
site_favicon: images/favicon.ico
extra:
  logo: images/siddhi-logo-w.svg
  palette:
    primary: teal
    accent: teal
google_analytics:
- UA-103065-28
- auto
pages:
- Welcome to WSO2 Siddhi Map Text: index.md
- API Docs:
  - 1.0.18: api/1.0.18.md
  - 1.0.17: api/1.0.17.md
  - 1.0.16: api/1.0.16.md
  - 1.0.15: api/1.0.15.md
  - 1.0.14: api/1.0.14.md
  - latest: api/latest.md
- License: license.md
theme: material
